"""HTML Report generator — converts an explanation dict into a self-contained HTML file."""

from datetime import date


_CSS = """
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
       background: #f5f5f5; color: #1a1a1a; padding: 32px 16px; }
.container { max-width: 860px; margin: 0 auto; }
header { background: #0f172a; color: white; border-radius: 8px; padding: 28px 32px; margin-bottom: 24px; }
header h1 { font-size: 20px; font-weight: 600; margin-bottom: 4px; }
header .sub { font-size: 13px; opacity: 0.6; }
.summary-box { background: white; border-left: 4px solid #3b82f6; border-radius: 4px;
               padding: 20px 24px; margin-bottom: 24px; font-size: 15px; line-height: 1.7; }
.verdict-new  { border-color: #22c55e; }
.verdict-old  { border-color: #f59e0b; }
.block { background: white; border-radius: 8px; padding: 20px 24px; margin-bottom: 16px;
         box-shadow: 0 1px 3px rgba(0,0,0,0.06); }
.block h2 { font-size: 14px; font-weight: 600; color: #6b7280; text-transform: uppercase;
            letter-spacing: 0.05em; margin-bottom: 12px; }
.block .rule-tag { display: inline-block; font-size: 11px; background: #f3f4f6;
                   color: #374151; border-radius: 4px; padding: 2px 8px; margin-bottom: 12px; }
.block ul { list-style: none; }
.block ul li { font-size: 14px; line-height: 1.8; color: #374151; }
.block ul li::before { content: "→ "; color: #9ca3af; }
footer { font-size: 12px; color: #9ca3af; text-align: center; margin-top: 32px; }
"""


def _escape(s: str) -> str:
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def render_html(explanation: dict, ctx_snapshot: dict = None) -> str:
    regime = explanation.get("regime_recommendation", "new_regime")
    verdict_class = "verdict-new" if regime == "new_regime" else "verdict-old"
    name = _escape(explanation.get("taxpayer_name", "Taxpayer"))
    ay = _escape(explanation.get("assessment_year", "AY2025-26"))
    case_id = _escape(explanation.get("case_id", ""))
    summary = _escape(explanation.get("summary", ""))

    blocks_html = ""
    for block in explanation.get("blocks", []):
        rule_id = _escape(block.get("rule_id", ""))
        heading = _escape(block.get("heading", ""))
        lines_html = "".join(
            f"<li>{_escape(line)}</li>" for line in block.get("lines", [])
        )
        blocks_html += f"""
        <div class="block">
          <span class="rule-tag">{rule_id}</span>
          <h2>{heading}</h2>
          <ul>{lines_html}</ul>
        </div>"""

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Jarviz Tax Decision — {name} — {ay}</title>
<style>{_CSS}</style>
</head>
<body>
<div class="container">
  <header>
    <h1>Jarviz Tax Decision Report</h1>
    <div class="sub">{name} &nbsp;·&nbsp; {ay} &nbsp;·&nbsp; Case {case_id} &nbsp;·&nbsp; Generated {date.today().isoformat()}</div>
  </header>

  <div class="summary-box {verdict_class}">
    {summary}
  </div>

  {blocks_html}

  <footer>
    Generated by Jarviz Rule Executor · All decisions traceable to Evidence → Rule → Statute
    · This report is for informational purposes only.
  </footer>
</div>
</body>
</html>"""
